     
#server.port=80
#server.port.a=true
#server.port.b=true

# 自定义的配置参数
#myUploadPath: d:/c76_toyshop/

server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/c76-s3-toyshop
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  # 静态资源映射
  resources:
     staticLocations: 
        - classpath:/resources/
        - classpath:/static/
        - file:${myUploadPath}



